# SPRING
spring:
  redis:
    host: 192.168.0.106
    port: 6379
    password:
  datasource:
    master:
      url: jdbc:mysql://39.105.17.34:8306/gps?autoReconnect=true&useSSL=false&allowMultiQueries=true
      username: root
      password: 1234567
      driverClassName: com.mysql.jdbc.Driver

