# SPRING
spring:
  redis:
    host: 192.168.0.106
    port: 6379
    password:
  datasource:
    master:
      url: jdbc:mysql://192.168.0.106:3306/gps?autoReconnect=true&useSSL=false&allowMultiQueries=true
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
